/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    ContactForm: typeof import('./components/contact/ContactForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSlider: typeof import('./components/home/HeroSlider.vue')['default']
    NewsletterSection: typeof import('./components/home/NewsletterSection.vue')['default']
    PricingPlans: typeof import('./components/pricing/PricingPlans.vue')['default']
    RecentProjects: typeof import('./components/home/RecentProjects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCounter: typeof import('./components/home/StatsCounter.vue')['default']
    StrengthsSection: typeof import('./components/home/StrengthsSection.vue')['default']
    TeamSection: typeof import('./components/about/TeamSection.vue')['default']
  }
}
